{
  "Uuid": "7c0fe645-40dd-4554-a12c-9845bd5bfe00",
  "IsCustomNode": true,
  "Category": "JNO",
  "Description": "Creates an XY plane at the given Z height",
  "Name": "XY_Plane_at_Z_level",
  "ElementResolver": {
    "ResolutionMap": {
      "Math": {
        "Key": "DSCore.Math",
        "Value": "DSCoreNodes.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Line": {
        "Key": "Autodesk.DesignScript.Geometry.Line",
        "Value": "ProtoGeometry.dll"
      },
      "Level": {
        "Key": "Revit.Elements.Level",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bb85c7429eee45f8add7011ef4a51f2c",
      "Inputs": [
        {
          "Id": "5604308cc9594c6189dcc62969df0594",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bd3f05d540724291b486b957101b3af4",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "996e2af73cea4e4da7891b6d57f317ea",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4c975b88f5de439cba69ef69e557751e",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "22636cadd13e439782005c3a36f988ab",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "630949c8b25346829f1448b2735b5e69",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "a10a83ff995949b7a6506f0e383c9f87",
      "Inputs": [
        {
          "Id": "3083b332146e43ee8023ea0cd71d5a8a",
          "Name": "origin",
          "Description": "Origin point of plane\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4bdc6cddab6744b2923b3575aaedb2a4",
          "Name": "normal",
          "Description": "Normal direction vector of plane\n\nVector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d15d59249b2641a0bcb243cdbcf098fc",
          "Name": "Plane",
          "Description": "Plane created by origin and normal",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Plane",
      "Id": "7ee94eb92cec487c8894e056efdb0411",
      "Inputs": [
        {
          "Id": "cb7b046822fc4eb286e42463fdade37a",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "Z_height",
        "TypeName": "int",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "8fa64ea4a3b347178e8c8f63895313c5",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "56840dced86240e2985faaf5a18ffb4d",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    }
  ],
  "Connectors": [
    {
      "Start": "4c975b88f5de439cba69ef69e557751e",
      "End": "3083b332146e43ee8023ea0cd71d5a8a",
      "Id": "0b703ea3205a43e597fcad0ae93bb124"
    },
    {
      "Start": "630949c8b25346829f1448b2735b5e69",
      "End": "4bdc6cddab6744b2923b3575aaedb2a4",
      "Id": "62970fe4f1f14705a81ef8e3a58bdf28"
    },
    {
      "Start": "d15d59249b2641a0bcb243cdbcf098fc",
      "End": "cb7b046822fc4eb286e42463fdade37a",
      "Id": "7f090f0498ce4530943613aa4e3bbee9"
    },
    {
      "Start": "56840dced86240e2985faaf5a18ffb4d",
      "End": "996e2af73cea4e4da7891b6d57f317ea",
      "Id": "b5a4ad07491940c2b5f2a2d24b43b419"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.0.5650",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -1291.419921875,
      "EyeY": 22096.607421875,
      "EyeZ": 25859.544921875,
      "LookX": 13491.419921875,
      "LookY": -22096.607421875,
      "LookZ": -28684.544921875,
      "UpX": 0.16287457942962646,
      "UpY": 0.92387974262237549,
      "UpZ": -0.34629198908805847
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "bb85c7429eee45f8add7011ef4a51f2c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 4.6903652886768441
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "22636cadd13e439782005c3a36f988ab",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 313.30677945947718,
        "Y": 158.86906002057765
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.ByOriginNormal",
        "Id": "a10a83ff995949b7a6506f0e383c9f87",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 483.08798528854095,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "7ee94eb92cec487c8894e056efdb0411",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 753.087985288541,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "8fa64ea4a3b347178e8c8f63895313c5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -0.56953060049096393,
        "Y": 52.447390428262565
      }
    ],
    "Annotations": [],
    "X": 285.76216364740822,
    "Y": 325.81326314794813,
    "Zoom": 1.33823125
  }
}